### ISSUE TITLE
Criação da página Sobre

### ISSUE THREAD

**Issue by leoarauj** [leokidson/github-master#3]
Poderia criar a página Sobre?

**Comment by leokidson** [comment]
A página está em produção

**Comment by leoarauj** [comment]
Obrigado, estou aguardando!
________________________________
De: Leonardo Araújo <notifications@github.com>
Enviado: segunda-feira, 20 de janeiro de 2020 07:37
Para: leokidson/github-master <github-master@noreply.github.com>
Cc: leoarauj <leo.arauj@outlook.com>; Author <author@noreply.github.com>
Assunto: Re: [leokidson/github-master] Criação da página Sobre (#3)


A página está em produção
